export const LIST_BANKS_REQUEST = 'LIST_BANKS_REQUEST';
export const LIST_BANKS_SUCCESS = 'LIST_BANKS_SUCCESS';
export const LIST_BANKS_FAILURE = 'LIST_BANKS_FAILURE';

export const SEND_TRANSACTION_REQUEST = 'SEND_TRANSACTION_REQUEST';
export const SEND_TRANSACTION_SUCCESS = 'SEND_TRANSACTION_SUCCESS';
export const SEND_TRANSACTION_FAILURE = 'SEND_TRANSACTION_FAILURE';