export const SEND_TRANSACTION_REQUEST = 'SEND_TRANSACTION_REQUEST';
export const SEND_TRANSACTION_SUCCESS = 'SEND_TRANSACTION_SUCCESS';
export const SEND_TRANSACTION_FAILURE = 'SEND_TRANSACTION_FAILURE';

export const DEL_TRANSACTION_REQUEST = 'DEL_TRANSACTION_REQUEST';
export const DEL_TRANSACTION_SUCCESS = 'DEL_TRANSACTION_SUCCESS';
export const DEL_TRANSACTION_FAILURE = 'DEL_TRANSACTION_FAILURE';

export const GET_LIST_TRANSACTION_REQUEST = 'GET_LIST_TRANSACTION_REQUEST';
export const GET_LIST_TRANSACTION_SUCCESS = 'GET_LIST_TRANSACTION_SUCCESS';
export const GET_LIST_TRANSACTION_FAILURE = 'GET_LIST_TRANSACTION_FAILURE';
